/**
 * generated by Xtext 2.14.0
 */
package org.robot.dsl.ui.contentassist;

import org.robot.dsl.ui.contentassist.AbstractRobotDslProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class RobotDslProposalProvider extends AbstractRobotDslProposalProvider {
}
