/*
 * generated by Xtext 2.14.0
 */
package org.robot.dsl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class RobotDslRuntimeModule extends AbstractRobotDslRuntimeModule {
}
