/*
 * generated by Xtext 2.14.0
 */
package org.robot.dsl.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import org.robot.dsl.services.RobotDslGrammarAccess;
import org.robot.model.robot.Connection;
import org.robot.model.robot.ExecuteStatement;
import org.robot.model.robot.ForwardStatement;
import org.robot.model.robot.ObjectAheadCondition;
import org.robot.model.robot.PrintStatement;
import org.robot.model.robot.RightStatement;
import org.robot.model.robot.Robot;
import org.robot.model.robot.RobotPackage;
import org.robot.model.robot.Scenario;
import org.robot.model.robot.StatementBlock;
import org.robot.model.robot.UntilStatement;
import org.robot.model.robot.WhileStatement;

@SuppressWarnings("all")
public class RobotDslSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private RobotDslGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == RobotPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case RobotPackage.CONNECTION:
				sequence_Connection(context, (Connection) semanticObject); 
				return; 
			case RobotPackage.EXECUTE_STATEMENT:
				sequence_ExecuteStatement(context, (ExecuteStatement) semanticObject); 
				return; 
			case RobotPackage.FORWARD_STATEMENT:
				if (rule == grammarAccess.getStatementRule()
						|| rule == grammarAccess.getControlStatementRule()) {
					sequence_ControlStatement_ForwardStatement(context, (ForwardStatement) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getForwardStatementRule()) {
					sequence_ForwardStatement(context, (ForwardStatement) semanticObject); 
					return; 
				}
				else break;
			case RobotPackage.OBJECT_AHEAD_CONDITION:
				sequence_ObjectAheadCondition(context, (ObjectAheadCondition) semanticObject); 
				return; 
			case RobotPackage.PRINT_STATEMENT:
				sequence_PrintStatement(context, (PrintStatement) semanticObject); 
				return; 
			case RobotPackage.RIGHT_STATEMENT:
				if (rule == grammarAccess.getStatementRule()
						|| rule == grammarAccess.getControlStatementRule()) {
					sequence_ControlStatement_RightStatement(context, (RightStatement) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getRightStatementRule()) {
					sequence_RightStatement(context, (RightStatement) semanticObject); 
					return; 
				}
				else break;
			case RobotPackage.ROBOT:
				sequence_Robot(context, (Robot) semanticObject); 
				return; 
			case RobotPackage.SCENARIO:
				sequence_Scenario(context, (Scenario) semanticObject); 
				return; 
			case RobotPackage.STATEMENT_BLOCK:
				sequence_StatementBlock(context, (StatementBlock) semanticObject); 
				return; 
			case RobotPackage.UNTIL_STATEMENT:
				sequence_UntilStatement(context, (UntilStatement) semanticObject); 
				return; 
			case RobotPackage.WHILE_STATEMENT:
				sequence_WhileStatement(context, (WhileStatement) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     Connection returns Connection
	 *
	 * Constraint:
	 *     (ip=EString port=INT)
	 */
	protected void sequence_Connection(ISerializationContext context, Connection semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, RobotPackage.Literals.CONNECTION__IP) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, RobotPackage.Literals.CONNECTION__IP));
			if (transientValues.isValueTransient(semanticObject, RobotPackage.Literals.CONNECTION__PORT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, RobotPackage.Literals.CONNECTION__PORT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getConnectionAccess().getIpEStringParserRuleCall_1_0(), semanticObject.getIp());
		feeder.accept(grammarAccess.getConnectionAccess().getPortINTTerminalRuleCall_3_0(), semanticObject.getPort());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Statement returns ForwardStatement
	 *     ControlStatement returns ForwardStatement
	 *
	 * Constraint:
	 *     value=INT?
	 */
	protected void sequence_ControlStatement_ForwardStatement(ISerializationContext context, ForwardStatement semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Statement returns RightStatement
	 *     ControlStatement returns RightStatement
	 *
	 * Constraint:
	 *     value=INT?
	 */
	protected void sequence_ControlStatement_RightStatement(ISerializationContext context, RightStatement semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Statement returns ExecuteStatement
	 *     ExecuteStatement returns ExecuteStatement
	 *
	 * Constraint:
	 *     destination=[Scenario|EString]
	 */
	protected void sequence_ExecuteStatement(ISerializationContext context, ExecuteStatement semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, RobotPackage.Literals.EXECUTE_STATEMENT__DESTINATION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, RobotPackage.Literals.EXECUTE_STATEMENT__DESTINATION));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getExecuteStatementAccess().getDestinationScenarioEStringParserRuleCall_2_0_1(), semanticObject.eGet(RobotPackage.Literals.EXECUTE_STATEMENT__DESTINATION, false));
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     ForwardStatement returns ForwardStatement
	 *
	 * Constraint:
	 *     {ForwardStatement}
	 */
	protected void sequence_ForwardStatement(ISerializationContext context, ForwardStatement semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Condition returns ObjectAheadCondition
	 *     ObjectAheadCondition returns ObjectAheadCondition
	 *
	 * Constraint:
	 *     {ObjectAheadCondition}
	 */
	protected void sequence_ObjectAheadCondition(ISerializationContext context, ObjectAheadCondition semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Statement returns PrintStatement
	 *     PrintStatement returns PrintStatement
	 *
	 * Constraint:
	 *     text=EString
	 */
	protected void sequence_PrintStatement(ISerializationContext context, PrintStatement semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, RobotPackage.Literals.PRINT_STATEMENT__TEXT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, RobotPackage.Literals.PRINT_STATEMENT__TEXT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getPrintStatementAccess().getTextEStringParserRuleCall_2_0(), semanticObject.getText());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     RightStatement returns RightStatement
	 *
	 * Constraint:
	 *     {RightStatement}
	 */
	protected void sequence_RightStatement(ISerializationContext context, RightStatement semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Robot returns Robot
	 *
	 * Constraint:
	 *     (name=EString connection=Connection? (scenarii+=Scenario scenarii+=Scenario*)? global=StatementBlock initial=[Scenario|EString])
	 */
	protected void sequence_Robot(ISerializationContext context, Robot semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Scenario returns Scenario
	 *
	 * Constraint:
	 *     (name=EString statementBlock=StatementBlock)
	 */
	protected void sequence_Scenario(ISerializationContext context, Scenario semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, RobotPackage.Literals.NAMED_ELEMENT__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, RobotPackage.Literals.NAMED_ELEMENT__NAME));
			if (transientValues.isValueTransient(semanticObject, RobotPackage.Literals.SCENARIO__STATEMENT_BLOCK) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, RobotPackage.Literals.SCENARIO__STATEMENT_BLOCK));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getScenarioAccess().getNameEStringParserRuleCall_2_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getScenarioAccess().getStatementBlockStatementBlockParserRuleCall_3_0(), semanticObject.getStatementBlock());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     StatementBlock returns StatementBlock
	 *
	 * Constraint:
	 *     (statements+=Statement statements+=Statement*)?
	 */
	protected void sequence_StatementBlock(ISerializationContext context, StatementBlock semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Statement returns UntilStatement
	 *     ConditionalStatement returns UntilStatement
	 *     UntilStatement returns UntilStatement
	 *
	 * Constraint:
	 *     (condition=Condition statementBlock=StatementBlock)
	 */
	protected void sequence_UntilStatement(ISerializationContext context, UntilStatement semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, RobotPackage.Literals.CONDITIONAL_STATEMENT__CONDITION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, RobotPackage.Literals.CONDITIONAL_STATEMENT__CONDITION));
			if (transientValues.isValueTransient(semanticObject, RobotPackage.Literals.CONDITIONAL_STATEMENT__STATEMENT_BLOCK) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, RobotPackage.Literals.CONDITIONAL_STATEMENT__STATEMENT_BLOCK));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getUntilStatementAccess().getConditionConditionParserRuleCall_2_0(), semanticObject.getCondition());
		feeder.accept(grammarAccess.getUntilStatementAccess().getStatementBlockStatementBlockParserRuleCall_3_0(), semanticObject.getStatementBlock());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Statement returns WhileStatement
	 *     ConditionalStatement returns WhileStatement
	 *     WhileStatement returns WhileStatement
	 *
	 * Constraint:
	 *     (condition=Condition statementBlock=StatementBlock)
	 */
	protected void sequence_WhileStatement(ISerializationContext context, WhileStatement semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, RobotPackage.Literals.CONDITIONAL_STATEMENT__CONDITION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, RobotPackage.Literals.CONDITIONAL_STATEMENT__CONDITION));
			if (transientValues.isValueTransient(semanticObject, RobotPackage.Literals.CONDITIONAL_STATEMENT__STATEMENT_BLOCK) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, RobotPackage.Literals.CONDITIONAL_STATEMENT__STATEMENT_BLOCK));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getWhileStatementAccess().getConditionConditionParserRuleCall_2_0(), semanticObject.getCondition());
		feeder.accept(grammarAccess.getWhileStatementAccess().getStatementBlockStatementBlockParserRuleCall_3_0(), semanticObject.getStatementBlock());
		feeder.finish();
	}
	
	
}
