/*
 * generated by Xtext 2.14.0
 */
package org.robot.dsl.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import org.robot.dsl.RobotDslRuntimeModule
import org.robot.dsl.RobotDslStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class RobotDslIdeSetup extends RobotDslStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new RobotDslRuntimeModule, new RobotDslIdeModule))
	}
	
}
