/**
 * generated by Xtext 2.14.0
 */
package org.robot.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.robot.dsl.ui.AbstractRobotDslUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class RobotDslUiModule extends AbstractRobotDslUiModule {
  public RobotDslUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
