<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="robot" nsURI="http://org/robot" nsPrefix="robot">
  <eClassifiers xsi:type="ecore:EClass" name="Robot" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="scenarii" upperBound="-1"
        eType="#//Scenario" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="global" lowerBound="1"
        eType="#//StatementBlock" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initial" eType="#//Scenario"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connection" eType="#//Connection"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Scenario" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statementBlock" lowerBound="1"
        eType="#//StatementBlock" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Connection">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ip" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="port" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectAheadCondition" eSuperTypes="#//Condition"/>
  <eClassifiers xsi:type="ecore:EClass" name="TrueCondition" eSuperTypes="#//Condition"/>
  <eClassifiers xsi:type="ecore:EClass" name="Condition"/>
  <eClassifiers xsi:type="ecore:EClass" name="ConditionalStatement" abstract="true"
      eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" lowerBound="1"
        eType="#//Condition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statementBlock" lowerBound="1"
        eType="#//StatementBlock" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ControlStatement" abstract="true" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExecuteStatement" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="destination" lowerBound="1"
        eType="#//Scenario"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ForwardStatement" eSuperTypes="#//ControlStatement"/>
  <eClassifiers xsi:type="ecore:EClass" name="IfStatement" eSuperTypes="#//ConditionalStatement"/>
  <eClassifiers xsi:type="ecore:EClass" name="PrintStatement" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RightStatement" eSuperTypes="#//ControlStatement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Statement" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="StatementBlock">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statements" upperBound="-1"
        eType="#//Statement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UntilStatement" eSuperTypes="#//ConditionalStatement"/>
  <eClassifiers xsi:type="ecore:EClass" name="WhileStatement" eSuperTypes="#//ConditionalStatement"/>
</ecore:EPackage>
