/**
 * generated by Xtext 2.14.0
 */
package org.robot.dsl;

import org.robot.dsl.RobotDslStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class RobotDslStandaloneSetup extends RobotDslStandaloneSetupGenerated {
  public static void doSetup() {
    new RobotDslStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
