/**
 * generated by Xtext 2.14.0
 */
package org.robot.dsl;

import org.robot.dsl.AbstractRobotDslRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class RobotDslRuntimeModule extends AbstractRobotDslRuntimeModule {
}
