/*
 * generated by Xtext 2.14.0
 */
package org.robot.dsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.robot.dsl.ui.internal.DslActivator;

public class RobotDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DslActivator.getInstance().getInjector("org.robot.dsl.RobotDsl");
	}

}
