/*
 * generated by Xtext 2.14.0
 */
package org.robot.dsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.robot.dsl.parser.antlr.internal.InternalRobotDslParser;
import org.robot.dsl.services.RobotDslGrammarAccess;

public class RobotDslParser extends AbstractAntlrParser {

	@Inject
	private RobotDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalRobotDslParser createParser(XtextTokenStream stream) {
		return new InternalRobotDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Robot";
	}

	public RobotDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(RobotDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
