/**
 * generated by Xtext 2.14.0
 */
package org.robot.dsl.ide;

import org.robot.dsl.ide.AbstractRobotDslIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class RobotDslIdeModule extends AbstractRobotDslIdeModule {
}
