/*
 * generated by Xtext 2.14.0
 */
package org.robot.dsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractRobotDslScopeProvider extends DelegatingScopeProvider {
}
