/*
 * generated by Xtext 2.14.0
 */
package org.robot.dsl.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class RobotDslProposalProvider extends AbstractRobotDslProposalProvider {
}
